"""Shared constants for mock merchant and tax jurisdiction configuration."""

MERCHANTS = [
    {
        "id": "merch_acme_foods",
        "name": "Acme Foods Co",
        "currency": "usd",
        "shopify_stores": ["acme-foods-main"],
        "b2b_ratio": 0.03,
        "dirty_profile": "missing_billing_zip",
    },
    {
        "id": "merch_ridge_gear",
        "name": "Ridge Gear Inc",
        "currency": "usd",
        "shopify_stores": ["ridge-gear-us", "ridge-gear-ca"],
        "b2b_ratio": 0.10,
        "dirty_profile": "duplicate_cross_store",
    },
    {
        "id": "merch_nova_health",
        "name": "Nova Health Supplies",
        "currency": "usd",
        "shopify_stores": ["nova-health-b2b"],
        "b2b_ratio": 0.20,
        "dirty_profile": "missing_exemption_certs",
    },
    {
        "id": "merch_surf_co",
        "name": "Surf Co Collective",
        "currency": "eur",
        "shopify_stores": ["surf-co-eu"],
        "b2b_ratio": 0.04,
        "dirty_profile": "currency_mismatch",
    },
    {
        "id": "merch_graze_box",
        "name": "Graze Box Snacks",
        "currency": "usd",
        "shopify_stores": ["graze-box-dtc"],
        "b2b_ratio": 0.02,
        "dirty_profile": "orphan_refunds",
    },
]

TAXABLE_STATES = [
    # High-volume commerce states
    "CA",
    "TX",
    "NY",
    "FL",
    "WA",
    "IL",
    "PA",
    "OH",
    "GA",
    "NC",
    "NJ",
    "VA",
    "AZ",
    "TN",
    "CO",
    "IN",
    "MO",
    "MI",
    "WI",
    "MN",
    "SC",
    "AL",
    "KY",
    "MA",
    # Mid-tier states
    "CT",
    "MD",
    "RI",
    "ID",
    "KS",
    "MS",
    "NE",
    "NV",
    "NM",
    "ND",
    "OK",
    "SD",
    "UT",
    "VT",
    "WV",
    "WY",
    "HI",
    "AR",
    "LA",
    "ME",
    "IA",
]

NO_TAX_STATES = ["OR", "MT", "NH", "DE", "AK"]
